import type { GuideQuestion } from "./questions";

export const PROPOSAL_YEARS = ["2026", "2027", "2028", "2029", "2030"] as const;

export function emptyProposalAnswers(): Record<string, string> {
  return {
    projectName: "",
    program: "Education (MTI / IMCA Weekend School)",
    projectStatus: "New",
    cycleNumber: "",
    importance: "",
    description: "",
    strategicObjectives: "",
    issuesPreconditions: "",
    yearlyObjectives: "",
    yearlyBudget: "",
    country: "United States — Central Indiana (Indianapolis)",
    beneficiary: "",
    beneficiaryType: "Community / Nonprofit beneficiaries",
    targetedGroup: "",
    expectedNumber: "",
    partnerships: "",
    stakeholders: "",
    logframeImpact: "",
    logframeOutcomes: "",
    logframeOutputs: "",
    logframeActivities: "",
    risks: "",
    startDate: "",
    endDate: "",
    milestones: "",
    costMethod: "Estimated",
    costSetter: "Implementer",
    activityCosts: "",
    cashFlowNotes: "",
    preparedBy: "",
  };
}

export const PROPOSAL_QUESTIONS: GuideQuestion[] = [
  {
    id: "preparedBy",
    prompt: "Who is preparing this project proposal?",
    help: "Name and role — appears on the proposal cover for Board / ED review.",
    type: "text",
    placeholder: "e.g., Amina Hassan — Youth Council Lead",
    required: true,
    suggestions: [
      "Executive Director",
      "Program Lead — Masjid Al-Fajr",
      "Youth Council Chair",
      "Development / Fundraising Lead",
      "Board Subcommittee Chair",
    ],
  },
  {
    id: "projectName",
    prompt: "What is the Project Name?",
    help: "Keep it clear and specific — this is the title on GR-F-07 style forms.",
    type: "text",
    required: true,
    placeholder: "e.g., IMCA Youth Leadership Academy 2026",
    suggestions: [
      "IMCA Youth Leadership Academy",
      "Masjid Al-Fajr Congregational Engagement Initiative",
      "IMCA Donor Stewardship & Endowment Launch",
      "Al-Ilm Weekend School Quality Strengthening Project",
      "IMCA Food Pantry Expansion & Volunteer System",
      "Women’s Council Community Wellness Series",
      "IMCA 3.0 Governance & Policy Upgrade",
      "Campus Facilities Safety & Modernization Phase 1",
    ],
  },
  {
    id: "program",
    prompt: "Which Program does this project sit under?",
    help: "Map to an IMCA program area so budgeting and reporting stay organized.",
    type: "select",
    required: true,
    options: [
      { value: "Education (MTI / IMCA Weekend School)", label: "Education (MTI / IMCA Weekend School)" },
      { value: "Youth Development (Youth Council)", label: "Youth Development (Youth Council)" },
      { value: "Women’s Empowerment (Women’s Council)", label: "Women’s Empowerment (Women’s Council)" },
      { value: "Social Services", label: "Social Services" },
      { value: "Community Engagement (Masjid Al-Fajr / Councils)", label: "Community Engagement (Masjid Al-Fajr / Councils)" },
      { value: "Operations (Events / Marketing / Facilities)", label: "Operations (Events / Marketing / Facilities)" },
      { value: "Organizational Development (IMCA 3.0)", label: "Organizational Development (IMCA 3.0)" },
      { value: "Fundraising & Donor Stewardship", label: "Fundraising & Donor Stewardship" },
      { value: "Facilities & Capital Development", label: "Facilities & Capital Development" },
    ],
  },
  {
    id: "projectStatus",
    prompt: "Is this a New project or a Repeated cycle?",
    help: "Matches the Project status field on the grant/proposal form.",
    type: "select",
    required: true,
    options: [
      { value: "New", label: "New" },
      { value: "Repeated", label: "Repeated — continuing cycle" },
    ],
  },
  {
    id: "cycleNumber",
    prompt: "If Repeated, what is the current cycle number? (otherwise type N/A)",
    help: "Example: Cycle 3 of an annual youth camp.",
    type: "text",
    placeholder: "N/A or e.g., 3",
    required: true,
    suggestions: ["N/A", "1", "2", "3", "4", "5"],
  },
  {
    id: "importance",
    prompt: "Why is this project important now?",
    help: "Project importance — explain urgency, community need, and link to IMCA 3.0 / mission.",
    type: "textarea",
    required: true,
    placeholder: "Explain why IMCA should prioritize this…",
    suggestions: [
      "Addresses a documented community gap and supports IMCA’s mission to build a vibrant, sustainable Muslim community in Central Indiana, with youth at the forefront.",
      "Critical to IMCA 3.0 financial sustainability by professionalizing donor stewardship and endowment development for long-term institutional health.",
      "Strengthens educational quality and family trust in MTI / Al-Ilm, which are core Islamic institutions serving current and future generations.",
      "Improves operational excellence and governance systems so IMCA can scale services safely, transparently, and with Board-ready reporting.",
      "Responds to rising social needs (food security, wellness, funeral support) while preserving dignity and Shariah-compliant stewardship of charitable funds.",
    ],
  },
  {
    id: "description",
    prompt: "Write the Project Description.",
    help: "Summarize what will be done, for whom, where, and over what period. Aim for 1–2 short paragraphs.",
    type: "textarea",
    required: true,
    suggestions: [
      "This project will design and deliver a structured program for IMCA community members in Indianapolis, combining faith-centered content, practical activities, volunteer engagement, and measurable outcomes aligned to IMCA 3.0 priorities. Implementation will include planning, delivery, monitoring, and Board reporting within the approved period.",
      "The project expands IMCA’s capacity to serve beneficiaries through coordinated activities across Masjid Al-Fajr and related entities. It includes stakeholder engagement, trained volunteers/staff, clear milestones, and a monitoring framework using Balanced Scorecard indicators.",
      "Working under IMCA’s Organizational Transformation Initiative, this project upgrades systems, communications, and service delivery so programs become more effective, sustainable, and easier to evaluate for Board and donor accountability.",
    ],
  },
  {
    id: "strategicObjectives",
    prompt: "List Strategic Objectives this project will help achieve (with indicators & targets).",
    help: "One objective per line. Format: Objective | Indicator | Target",
    type: "textarea",
    required: true,
    placeholder:
      "Increase youth leadership readiness | % youth completing leadership pathway | 80% by Dec 2027",
    suggestions: [
      "Strengthen community engagement | % increase in program participation vs. baseline | 25% increase within 12 months\nImprove spiritual learning outcomes | % participants reporting improved Islamic knowledge (survey) | ≥ 80% satisfied / improved\nAdvance IMCA 3.0 priority delivery | % project milestones completed on time | ≥ 90% milestone completion",
      "Grow sustainable funding | $ raised toward project / endowment goal | Meet 100% of annual fundraising target\nImprove donor retention | % major donors retained year-over-year | ≥ 85%\nIncrease partnership leverage | # active strategic partners contributing | ≥ 3 partners",
      "Improve process quality | % priority processes with documented owners & metrics | 100% of selected processes\nReduce service delays | Average cycle time for key service request | Reduce by 30%\nStrengthen transparency | On-time Board progress reports submitted | 4 quarterly reports / year",
    ],
  },
  {
    id: "issuesPreconditions",
    prompt: "What Issues and Preconditions will the project address?",
    help: "One row per line. Format: Issue | Precondition | Precondition Indicator | Target",
    type: "textarea",
    required: true,
    suggestions: [
      "Limited structured youth leadership pathway | Trained mentors and curriculum approved | # mentors onboarded / curriculum sessions ready | 8 mentors; 12 sessions ready before launch\nLow volunteer coordination | Shared calendar and role descriptions exist | % key roles filled with written SOPs | 100% of priority roles documented\nUneven communication across entities | Unified messaging guidelines adopted | Brand/communications checklist completed | Checklist approved by ED",
      "Donor relationships largely event-based | CRM / stewardship cadence established | % major donors on stewardship plan | 100% of major donors tagged in CRM\nRestricted-fund handling needs clearer SOPs | Finance policy refresher completed | Policy pack Board-approved | Policies approved before campaign launch\nLimited endowment awareness | Donor education materials published | # stewardship education touchpoints | ≥ 4 touchpoints / year",
      "Service demand exceeds volunteer capacity | Volunteer pipeline and shifts scheduled | Fill rate of critical volunteer shifts | ≥ 90% shift fill rate\nFamilies lack awareness of services | Outreach plan executed | # households reached with service info | Target set from baseline mapping",
    ],
  },
  {
    id: "yearlyObjectives",
    prompt: "If this is multi-year / ongoing, list objectives by year (2026–2030). Else write N/A.",
    help: "Format lines as: Year | Objective",
    type: "textarea",
    required: true,
    suggestions: [
      "N/A — single-cycle project within one fiscal year",
      "2026 | Launch pilot, establish baselines, recruit core team\n2027 | Scale delivery to full target cohort; refine curriculum/process\n2028 | Institutionalize SOPs; expand partnerships\n2029 | Achieve sustainability milestones (funding/volunteers)\n2030 | Evaluate impact; recommend next strategic cycle",
      "2026 | Complete design, branding, and Board approval\n2027 | Full implementation year + mid-course Lean improvement\n2028 | Optimize cost per beneficiary and document model for replication",
    ],
  },
  {
    id: "yearlyBudget",
    prompt: "What budget is required by year? (USD)",
    help: "Format: Year | Amount. Use best estimates — you can refine later in Budgeting Exercise.",
    type: "textarea",
    required: true,
    suggestions: [
      "2026 | 25000\n2027 | 30000\n2028 | 30000\n2029 | 28000\n2030 | 28000",
      "2026 | 12000\n2027 | 15000",
      "2026 | 75000\n2027 | 120000\n2028 | 100000",
      "2026 | 5000",
    ],
  },
  {
    id: "country",
    prompt: "Country / geography of implementation?",
    help: "Primary geography for beneficiary reporting.",
    type: "text",
    required: true,
    suggestions: [
      "United States — Central Indiana (Indianapolis)",
      "United States — Indiana (statewide partners; Indianapolis hub)",
    ],
  },
  {
    id: "beneficiary",
    prompt: "Who is the primary Beneficiary organization / community?",
    help: "Often IMCA entities and the Muslim community of Central Indiana.",
    type: "text",
    required: true,
    suggestions: [
      "Indianapolis Muslim Community Association (IMCA) community",
      "Masjid Al-Fajr congregants and families",
      "MTI School of Knowledge students and families",
      "Al-Ilm Weekend School students and families",
      "IMCA Food Pantry / social service recipients",
      "IMCA Youth Council participants",
    ],
  },
  {
    id: "beneficiaryType",
    prompt: "Beneficiary Type?",
    help: "High-level category used on the proposal form.",
    type: "select",
    required: true,
    options: [
      { value: "Community / Nonprofit beneficiaries", label: "Community / Nonprofit beneficiaries" },
      { value: "Students / Learners", label: "Students / Learners" },
      { value: "Youth", label: "Youth" },
      { value: "Women", label: "Women" },
      { value: "Families / Households in need", label: "Families / Households in need" },
      { value: "Institutional (IMCA internal capacity)", label: "Institutional (IMCA internal capacity)" },
      { value: "Donors / Partners", label: "Donors / Partners" },
    ],
  },
  {
    id: "targetedGroup",
    prompt: "Describe the Targeted Group more specifically.",
    help: "Age range, gender, membership status, need category, etc.",
    type: "textarea",
    required: true,
    suggestions: [
      "Muslim youth ages 13–18 in Central Indiana, with priority for active Masjid / school-connected families.",
      "Adult congregants seeking structured Islamic learning and community belonging.",
      "Households experiencing food insecurity within IMCA’s service radius.",
      "Current and prospective major donors ($1,000+ annual giving) and endowment prospects.",
      "IMCA staff, board committees, and volunteer leads responsible for program delivery.",
      "Women connected to IMCA Women’s Council seeking education, wellness, and service opportunities.",
    ],
  },
  {
    id: "expectedNumber",
    prompt: "Expected number of beneficiaries / participants?",
    help: "Use a numeric target (individuals, households, or students).",
    type: "text",
    required: true,
    suggestions: ["50", "100", "150", "250", "500", "1000"],
  },
  {
    id: "partnerships",
    prompt: "List Expected Partnerships.",
    help: "One per line: Partner Name | Type | Target Financial Contribution ($ or In-kind)",
    type: "textarea",
    required: true,
    suggestions: [
      "Local Muslim professional network | Technical / volunteer | In-kind mentoring (est. $5,000 value)\nCommunity grocery partners | In-kind goods | $8,000 equivalent food donations\nCivic / interfaith partner | Co-hosting | $0 cash; venue/ co-promotion in-kind",
      "IMCA Board Development Committee | Governance oversight | $0 (oversight)\nExternal foundation / grant partner | Grant funding | $25,000\nCorporate sponsor (local) | Sponsorship | $10,000",
      "MTI / Al-Ilm leadership | Implementing partner | In-kind staff time\nYouth Council | Implementing partner | In-kind volunteer hours",
      "No external cash partners at this stage | Internal IMCA | $0 — partnership development planned in Phase 1",
    ],
  },
  {
    id: "stakeholders",
    prompt: "List Stakeholders, their impact, influence, and evaluation.",
    help: "One per line: Stakeholder | Impact description | Influence (+ or -) | Evaluation (high/mid/low)",
    type: "textarea",
    required: true,
    suggestions: [
      "IMCA Board of Directors | Approves budget/policy and provides oversight | + | high\nExecutive Director | Accountable for delivery and reporting | + | high\nProgram volunteers | Deliver activities and shape community experience | + | high\nCongregants / families | Receive services; provide feedback and trust | + | high\nNeighboring community / civic partners | Perception and collaboration opportunities | + | mid",
      "Major donors | Enable funding; expect stewardship transparency | + | high\nFinance / Treasurer | Controls disbursements and compliance | + | high\nYouth participants | Core beneficiaries; influence peer enrollment | + | mid\nSchool administrators (MTI/Al-Ilm) | Coordination and scheduling | + | mid",
      "Regulatory / municipal authorities (as applicable) | Permits, compliance for events/facilities | +/- | mid\nMedia / public narrative | Affects brand reputation | +/- | low",
    ],
  },
  {
    id: "logframeImpact",
    prompt: "Logical Framework — Impact (one line).",
    help: "Format: Description | Target | Evidence | Assumption",
    type: "textarea",
    required: true,
    suggestions: [
      "A stronger, more sustainable IMCA that better serves Central Indiana Muslims across spiritual, educational, and social needs | Demonstrable improvement on agreed IMCA 3.0 scorecard goals by 2030 | Board scorecards, annual impact report, beneficiary surveys | Community trust and Board sponsorship of IMCA 3.0 remain strong",
      "Youth are prepared for faithful leadership and long-term belonging in the IMCA community | ≥ 70% of academy alumni remain engaged in IMCA service/leadership within 18 months | Alumni tracking sheet; Youth Council roster | Families continue to support youth participation",
    ],
  },
  {
    id: "logframeOutcomes",
    prompt: "Logical Framework — Outcomes (changes for people).",
    help: "One outcome per line: Description | Target | Evidence | Assumption",
    type: "textarea",
    required: true,
    suggestions: [
      "Participants increase knowledge, skills, or practice related to the project theme | ≥ 80% show improvement on pre/post measure | Pre/post assessment summary | Tools are administered consistently\nBeneficiaries report higher satisfaction / belonging | Satisfaction ≥ 85% | Survey results | Sample is representative\nVolunteer/staff capacity to deliver services improves | 100% priority roles trained | Training attendance + competency checklist | Turnover remains manageable",
      "Donor retention and stewardship quality improve | Major-donor retention ≥ 85% | CRM retention report | Economic conditions remain supportive\nTransparent reporting increases Board confidence | 100% quarterly reports on time | Board packet archive | Data systems are maintained",
    ],
  },
  {
    id: "logframeOutputs",
    prompt: "Logical Framework — Outputs (deliverables you can count).",
    help: "One output per line: Description | Target | Evidence | Assumption",
    type: "textarea",
    required: true,
    suggestions: [
      "Program sessions / workshops delivered | 12 sessions completed | Session logs & attendance | Venue and facilitators available\nParticipants enrolled and completing core pathway | 40 completers | Registration & completion roster | Recruitment targets met\nSOP / curriculum package produced | 1 approved package | Document version on file | Reviewers provide timely feedback\nCommunications assets published | 6 campaign posts/emails | Content calendar archive | Brand guidelines followed",
      "Donor stewardship touches completed | 4 touches/year for each major donor | CRM activity log | Donor contact data is current\nVolunteer shifts staffed | ≥ 90% fill rate | Shift schedule report | Recruiting pipeline is active",
    ],
  },
  {
    id: "logframeActivities",
    prompt: "Logical Framework — Activities (what the team will do).",
    help: "One activity per line: Description | Target | Evidence | Assumption",
    type: "textarea",
    required: true,
    suggestions: [
      "Form project team and RACI | Team chartered within 30 days | Kickoff notes + RACI sheet | Key roles accept assignments\nConduct needs / baseline assessment | Baseline completed before launch | Baseline brief | Respondents cooperate\nDesign curriculum / process & tools | Package ready 2 weeks pre-launch | Approved materials | Subject experts available\nRecruit and orient participants/volunteers | Recruitment target met | Signup list | Outreach channels work\nDeliver sessions / services on schedule | ≥ 90% sessions held as planned | Calendar + attendance | Facility conflicts minimized\nMonitor KPIs and report to Board | Quarterly reports submitted | Board packets | Data collected monthly\nClose-out evaluation and lessons learned | Final evaluation within 30 days of end | Evaluation memo | Stakeholders provide feedback",
      "Map assets and stakeholders | Asset map completed | Asset register | Departments share data\nProcure supplies / vendors | Procurement within budget | Purchase records | Vendors quote timely\nRun communications campaign | Campaign live before registration | Analytics screenshot | Platforms remain accessible",
    ],
  },
  {
    id: "risks",
    prompt: "Main Project Risks and Mitigation Measures.",
    help: "One per line: Risk | Mitigation",
    type: "textarea",
    required: true,
    suggestions: [
      "Low enrollment / participation | Early outreach via masjid announcements, schools, WhatsApp groups; early-bird registration\nVolunteer / staff burnout | Shared RACI, backup facilitators, realistic cadence\nBudget shortfall | Phased scope; donor/partner asks; contingency of 10%\nScheduling conflicts with Ramadan/Eid/school calendar | Build Islamic & school calendar into milestone plan at design stage\nData quality weak for reporting | Simple monthly tracker template; owner assigned",
      "Key-person dependency | Cross-training and written SOPs in Phase 1\nReputation / communication missteps | Unified messages reviewed by communications lead; sensitive topics escalated to ED\nFacility / AV unavailability | Backup room checklist; confirm bookings 2 weeks ahead\nPartner contribution delayed | Written partner MOU; alternate funding plan",
    ],
  },
  {
    id: "startDate",
    prompt: "Project start date?",
    help: "Implementation period start.",
    type: "text",
    required: true,
    placeholder: "YYYY-MM-DD",
  },
  {
    id: "endDate",
    prompt: "Project end date?",
    help: "Implementation period end.",
    type: "text",
    required: true,
    placeholder: "YYYY-MM-DD",
  },
  {
    id: "milestones",
    prompt: "List Project Milestones by phase.",
    help: "One per line: Phase | No. | Milestone | Months (e.g., Jan-Mar or 2026-Q1)",
    type: "textarea",
    required: true,
    suggestions: [
      "Phase 1 | 1.1 | Project kickoff & team RACI | Jan\nPhase 1 | 1.2 | Baseline / needs assessment | Jan-Feb\nPhase 1 | 1.3 | Design tools, curriculum, SOPs | Feb-Mar\nPhase 1 | 1.4 | Recruit participants & partners | Mar\nPhase 2 | 2.1 | Launch delivery | Apr\nPhase 2 | 2.2 | Mid-point monitoring review | Jun\nPhase 2 | 2.3 | Course-correct using Lean tools | Jul\nPhase 2 | 2.4 | Complete core delivery cycle | Sep\nPhase 3 | 3.1 | Stakeholder feedback survey | Oct\nPhase 3 | 3.2 | Board impact briefing | Nov\nPhase 3 | 3.3 | Documentation & knowledge capture | Nov-Dec\nPhase 3 | 3.4 | Close-out & next-year proposal | Dec",
      "Phase 1 | 1.1 | Board approval & budget lock | Month 1\nPhase 1 | 1.2 | Vendor/facility confirmations | Month 1-2\nPhase 2 | 2.1 | Full implementation | Month 3-8\nPhase 3 | 3.1 | Evaluation & sustainability plan | Month 9-10",
    ],
  },
  {
    id: "costMethod",
    prompt: "Cost Calculation Method?",
    help: "How were activity costs estimated? (Budgeting Exercise)",
    type: "select",
    required: true,
    options: [
      { value: "Estimated", label: "Estimated" },
      { value: "Previous project", label: "Previous project" },
      { value: "Based on a feasibility study", label: "Based on a feasibility study (attach later)" },
    ],
  },
  {
    id: "costSetter",
    prompt: "Who is the Cost Setter?",
    help: "Who prepared the cost figures?",
    type: "select",
    required: true,
    options: [
      { value: "Implementer", label: "Implementer" },
      { value: "Beneficiary", label: "Beneficiary" },
      { value: "Specialist", label: "Specialist" },
      { value: "Program Department", label: "Program Department" },
      { value: "Evaluation Team", label: "Evaluation Team" },
      { value: "Other", label: "Other (specify in activity notes)" },
    ],
  },
  {
    id: "activityCosts",
    prompt: "Budgeting Exercise — list activity costs.",
    help: "One per line: Activity | Cost (number only, USD). Total will be calculated.",
    type: "textarea",
    required: true,
    suggestions: [
      "Project management & coordination | 3000\nCurriculum / materials development | 1500\nFacilitator / speaker honoraria | 2000\nMarketing & communications | 800\nVenue / facilities / AV | 1200\nFood / hospitality | 1500\nSupplies & printing | 600\nVolunteer appreciation | 400\nMonitoring, evaluation & reporting | 500\nContingency (10%) | 1250",
      "Staff / contractor time | 8000\nSoftware / CRM / digital tools | 1200\nTraining workshops | 2500\nPrinting & donor materials | 900\nEvents / stewardship dinners | 3500\nContingency | 1600",
      "Design & planning | 2000\nImplementation delivery | 10000\nPartnership development | 1500\nEvaluation | 1000\nContingency | 1500",
    ],
  },
  {
    id: "cashFlowNotes",
    prompt: "Any notes on cash flow / installments by month?",
    help: "Optional but useful for finance. Example: 40% at kickoff, 40% mid, 20% close-out.",
    type: "textarea",
    suggestions: [
      "Suggested installments: 40% at start (planning/setup), 40% at midpoint delivery, 20% at close-out/evaluation.",
      "Monthly spend roughly level across active delivery months; heavier in launch month for materials and marketing.",
      "Major costs front-loaded in first quarter for procurement; recurring facilitator costs monthly thereafter.",
      "N/A — single disbursement upon Board approval.",
    ],
  },
];
